version: "3.8"

services:
  mariadb_server:
    image: library/mariadb:10.7.1
    restart: always
    container_name: mariadb_server
    hostname: mariadb_server
    volumes:
      - ./storage/mariadb/data:/var/lib/mysql
      - ./storage/mariadb/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      internal:
        ipv4_address: 6.1.0.2
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      BIND: 0.0.0.0
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: auth
      MARIADB_USER: auth
      MARIADB_PASSWORD: auth

  mongodb_server:
    image: mongo:8.0.3-noble
    restart: always
    command: mongod --config /etc/mongo/mongod.conf --auth
    container_name: mongodb_server
    hostname: mongodb_server
    volumes: 
      - ./storage/mongodb_storage/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./storage/mongodb_storage/configdb:/data/configdb
      - ./storage/mongodb_storage/data:/data/db
      - ./storage/mongodb_storage/mongod.conf:/etc/mongo/mongod.conf
    networks:
      internal:
        ipv4_address: 6.1.0.3
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: auth

  node_auth_server:
    image: node_auth_server
    restart: always
    container_name: node_auth_server
    hostname: node_auth_server
    networks:
      internal:
        ipv4_address: 6.1.0.4
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - mariadb_server

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 6.1.0.0/16
          gateway: 6.1.0.1