version: "3.8"

services:
  # 应用程序的核心开发服务器
  develop_server:
    image: 1569663570/centos792009_develop_server
    restart: always
    container_name: develop_server
    hostname: develop_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.2
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      
  # 管理后台 web 服务
  web_server:
    image: 1569663570/centos792009_web_server
    restart: always
    container_name: web_server
    hostname: web_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.6    
    ports:
      - 6680:80
    environment:
      TZ: Asia/Shanghai
      MARIADB_SERVER: mariadb_server      
      MARIADB_USER: teamtalk
      MARIADB_PASSWORD: teamtalk123@
      MARIADB_DATABASE: teamtalk
      MSFS_URL: msfs_server:8700
      HTTP_URL: http_msg_server:8400    
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
    depends_on:      
      - develop_server
      - redis_server
      - mariadb_server

  login_server:
    image: 1569663570/centos792009_login_server
    restart: always
    container_name: login_server
    hostname: login_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.10
    ports:
      - 8080:8080
      - 8008:8008
    environment:
      TZ: Asia/Shanghai
      MSFS_SERVER: msfs_server
      WEB_SERVER: web_server
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
    depends_on:
      - develop_server
      - redis_server
      - mariadb_server

  msg_server:
    image: 1569663570/centos792009_msg_server
    restart: always
    container_name: msg_server
    hostname: msg_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.17
    ports:
      - 8000:8000
    environment:
      TZ: Asia/Shanghai
      IP_ADDR1: 192.168.0.88
      IP_ADDR2: 192.168.1.88
      DB_PROXY_SERVER: db_proxy_server
      LOGIN_SERVER: login_server
      ROUTE_SERVER: route_server
      PUSH_SERVER: push_server
      FILE_SERVER: file_server
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
    depends_on:
      - develop_server
      - redis_server
      - mariadb_server

  db_proxy_server:
    image: 1569663570/centos792009_db_proxy_server
    restart: always
    container_name: db_proxy_server
    hostname: db_proxy_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.16
    ports:
      - 10600:10600
    environment:
      TZ: Asia/Shanghai
      MARIADB_SERVER_MASTER: mariadb_server
      MARIADB_SERVER_SLAVE: mariadb_server
      MARIADB_USER: teamtalk
      MARIADB_PASSWORD: teamtalk123@      
      MARIADB_DATABASE: teamtalk
      UNREAD_HOST: redis_server
      GROUP_SET_HOST: redis_server
      SYNC_HOST: redis_server
      TOKEN_HOST: redis_server
      GROUP_MEMBER_HOST: redis_server
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
    depends_on:
      - develop_server
      - redis_server
      - mariadb_server

  route_server:
    image: 1569663570/centos792009_route_server
    restart: always
    container_name: route_server
    hostname: route_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.15
    ports:
      - 8200:8200
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
    depends_on:
      - develop_server
      - redis_server
      - mariadb_server

  http_msg_server:
    image: 1569663570/centos792009_http_msg_server
    restart: always
    container_name: http_msg_server
    hostname: http_msg_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.14
    ports:
      - 8400:8400
    environment:
      TZ: Asia/Shanghai
      DB_SERVER_IP1: db_proxy_server
      ROUTE_SERVER_IP1: route_server
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
    depends_on:
      - develop_server
      - redis_server
      - mariadb_server

  push_server:
    image: 1569663570/centos792009_push_server
    restart: always
    container_name: push_server
    hostname: push_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.13
    ports:
      - 8500:8500
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
    depends_on:
      - develop_server
      - redis_server
      - mariadb_server

  file_server:
    image: 1569663570/centos792009_file_server
    restart: always
    container_name: file_server
    hostname: file_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.12
    ports:
      - 8600:8600
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
    depends_on:
      - develop_server
      - redis_server
      - mariadb_server

  msfs_server:
    image: 1569663570/centos792009_msfs_server
    restart: always
    container_name: msfs_server
    hostname: msfs_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.11
    ports:
      - 8700:8700
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
    depends_on:
      - develop_server
      - redis_server
      - mariadb_server

  mariadb_server:
    image: library/mariadb:10.7.1
    restart: always
    container_name: mariadb_server
    hostname: mariadb_server
    volumes:
      - ../mysql_data:/var/lib/mysql
      - ../auto_setup/mariadb/conf:/docker-entrypoint-initdb.d
    networks:
      teamtalk:
        ipv4_address: 6.1.0.8
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MARIADB_ROOT_PASSWORD: admin123@
      MARIADB_DATABASE: teamtalk
      MARIADB_USER: teamtalk
      MARIADB_PASSWORD: teamtalk123@
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"

  redis_server:
    image: 1569663570/centos792009_redis_server
    restart: always
    container_name: redis_server
    hostname: redis_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.7
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
      BIND: 0.0.0.0
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"

  core_proxy_server:
    image: 1569663570/core_proxy_server
    restart: always
    container_name: core_proxy_server
    hostname: core_proxy_server
    networks:
      teamtalk:
        ipv4_address: 6.1.0.3
    ports:
      # 反向代理服务器对 http 请求进行转发的端口
      - 80:80
      # 反向代理服务器对 tcp 请求进行转发的端口
      - 8081:8081
    environment:
      TZ: Asia/Shanghai
    extra_hosts:
      - "develop_server:6.1.0.2"
      - "core_proxy_server:6.1.0.3"
      - "login_server:6.1.0.10"
      - "msfs_server:6.1.0.11"      
      - "file_server:6.1.0.12"
      - "push_server:6.1.0.13"
      - "http_msg_server:6.1.0.14"
      - "route_server:6.1.0.15"
      - "db_proxy_server:6.1.0.16"
      - "msg_server:6.1.0.17"
      - "web_server:6.1.0.6"
      - "redis_server:6.1.0.7"
      - "mariadb_server:6.1.0.8"
    depends_on:
      - develop_server
      - login_server
      - msfs_server
      - file_server
      - push_server
      - http_msg_server
      - route_server
      - db_proxy_server
      - msg_server
      - web_server
      - redis_server
      - mariadb_server

# Docker 自定义网络，指定了该网络的子网和网关。每个服务都连接到这个网络，并分配了一个独特的 IPv4 地址，以便容器之间可以相互通信。
networks:
  teamtalk:
    driver: bridge
    ipam:
      config:
        - subnet: 6.1.0.0/16
          gateway: 6.1.0.1